pck600_ppu_smc_q:
    DEVCHAN_CFG: 1
    DEF_PWR_POLICY: 1000
    DEF_PWR_DYN_EN: 1
    DEF_OP_POLICY: 0000
    DEF_OP_DYN_EN: 0
    DEV_PREQ_DLY: 1
    PCSM_PREQ_DLY: 1
    ISO_CLKEN_DLY_CFG: 8
    CLKEN_RST_DLY_CFG: 0
    RST_HWSTAT_DLY_CFG: 1
    CLKEN_ISO_DLY_CFG: 2
    ISO_RST_DLY_CFG: 3
    FUNC_RET_RAM_REG_CFG: 0
    FULL_RET_RAM_REG_CFG: 0
    MEM_RET_RAM_REG_CFG: 0
    WARM_RST_DEVREQEN_CFG: 0
    DBG_RECOV_PORST_CFG: 0
    NUM_OPMODE_CFG: 0
    OP_ACTIVE_CFG: 0
    STA_POLICY_OP_IRQ_CFG: 0
    STA_POLICY_PWR_IRQ_CFG: 0
    LOCK_CFG: 1
    SW_DEV_DEL_CFG: 0
    PWR_MODE_ENTRY_DEL_CFG: 0
    STA_OFF_EMU_SPT_CFG: 1
    STA_MEM_RET_SPT_CFG: 0
    STA_MEM_RET_EMU_SPT_CFG: 0
    STA_LGC_RET_SPT_CFG: 0
    STA_FULL_RET_SPT_CFG: 1
    STA_MEM_OFF_SPT_CFG: 0
    STA_FUNC_RET_SPT_CFG: 1
    STA_DBG_RECOV_SPT_CFG: 0
    DYN_OFF_SPT_CFG: 1
    DYN_OFF_EMU_SPT_CFG: 1
    DYN_MEM_RET_SPT_CFG: 0
    DYN_MEM_RET_EMU_SPT_CFG: 0
    DYN_LGC_RET_SPT_CFG: 0
    DYN_FULL_RET_SPT_CFG: 1
    DYN_MEM_OFF_SPT_CFG: 0
    DYN_FUNC_RET_SPT_CFG: 1
    DYN_ON_SPT_CFG: 1
    DYN_WRM_RST_SPT_CFG: 0
    DEV_SYNC_EN: 0
    DEV_ACTIVE_SYNC_EN: 0
    PCSM_SYNC_EN: 1
    QCLK_SYNC_EN: 1
    OFF_MEM_RET_TRANS_CFG: 0
    PCSM_OFF_INIT: 1
    OPMODE_PCSM_SPT_CFG: 0
    UARCH: 1

pck600_lpd_q_smc:
    SEQUENCER:                1
    NUM_QCHL:                 2
    CTRL_Q_CH_SYNC:           1
    DEV_Q_CH_SYNC:            1
    DEV_QACTIVE_SYNC:         0
    ACTIVE_DENY:              0

pck600_ppu_ca53_core0_q:
    DEVCHAN_CFG:            1  
    DEV_PREQ_DLY:           1
    PCSM_PREQ_DLY:          1 
    DEF_PWR_POLICY:         1000
    DEF_PWR_DYN_EN: 1
    ISO_CLKEN_DLY_CFG:      8
    CLKEN_RST_DLY_CFG:      0
    RST_HWSTAT_DLY_CFG:     1
    CLKEN_ISO_DLY_CFG:      2
    ISO_RST_DLY_CFG:        3
    FUNC_RET_RAM_REG_CFG:   1
    FULL_RET_RAM_REG_CFG:   1
    MEM_RET_RAM_REG_CFG:    1
    WARM_RST_DEVREQEN_CFG:  1
    DBG_RECOV_PORST_CFG:    0
    STA_FUNC_RET_SPT_CFG:   1
    STA_MEM_OFF_SPT_CFG:    1
    STA_FULL_RET_SPT_CFG:   1
    STA_LGC_RET_SPT_CFG:    0
    STA_DBG_RECOV_SPT_CFG:  0
    STA_MEM_RET_EMU_SPT_CFG: 1
    STA_MEM_RET_SPT_CFG:    1
    STA_OFF_EMU_SPT_CFG:    1
    DYN_ON_SPT_CFG:         1
    DYN_FUNC_RET_SPT_CFG:   1
    DYN_MEM_OFF_SPT_CFG:    1
    DYN_FULL_RET_SPT_CFG:   1
    DYN_LGC_RET_SPT_CFG:    0
    DYN_MEM_RET_SPT_CFG:    1
    DYN_MEM_RET_EMU_SPT_CFG: 1
    DYN_OFF_EMU_SPT_CFG:    1
    DYN_OFF_SPT_CFG:        1
    DYN_WRM_RST_SPT_CFG:    0
    STA_POLICY_OP_IRQ_CFG:  0
    STA_POLICY_PWR_IRQ_CFG: 0
    LOCK_CFG:               0
    SW_DEV_DEL_CFG:         1
    PWR_MODE_ENTRY_DEL_CFG: 1
    DEF_OP_POLICY:          0b000
    NUM_OPMODE_CFG:         0
    DEF_OP_DYN_EN:          0
    OP_ACTIVE_CFG:          0
    DEV_SYNC_EN:            0
    DEV_ACTIVE_SYNC_EN:     0
    PCSM_SYNC_EN:           1
    QCLK_SYNC_EN:           1
    OFF_MEM_RET_TRANS_CFG:  0
    PCSM_OFF_INIT:          1
    OPMODE_PCSM_SPT_CFG:    0
    UARCH:                  1

pck600_ppu_ca53_neon_q:
    DEVCHAN_CFG:            1  
    DEV_PREQ_DLY:           1
    PCSM_PREQ_DLY:          1 
    DEF_PWR_POLICY:         1000
    DEF_PWR_DYN_EN: 1
    ISO_CLKEN_DLY_CFG:      8
    CLKEN_RST_DLY_CFG:      0
    RST_HWSTAT_DLY_CFG:     1
    CLKEN_ISO_DLY_CFG:      2
    ISO_RST_DLY_CFG:        3
    FUNC_RET_RAM_REG_CFG:   1
    FULL_RET_RAM_REG_CFG:   1
    MEM_RET_RAM_REG_CFG:    1
    WARM_RST_DEVREQEN_CFG:  1
    DBG_RECOV_PORST_CFG:    0
    STA_FUNC_RET_SPT_CFG:   1
    STA_MEM_OFF_SPT_CFG:    1
    STA_FULL_RET_SPT_CFG:   1
    STA_LGC_RET_SPT_CFG:    0
    STA_DBG_RECOV_SPT_CFG:  0
    STA_MEM_RET_EMU_SPT_CFG: 0
    STA_MEM_RET_SPT_CFG:    1
    STA_OFF_EMU_SPT_CFG:    0
    DYN_ON_SPT_CFG:         1
    DYN_FUNC_RET_SPT_CFG:   1
    DYN_MEM_OFF_SPT_CFG:    1
    DYN_FULL_RET_SPT_CFG:   1
    DYN_LGC_RET_SPT_CFG:    0
    DYN_MEM_RET_SPT_CFG:    1
    DYN_MEM_RET_EMU_SPT_CFG: 0
    DYN_OFF_EMU_SPT_CFG:    0
    DYN_OFF_SPT_CFG:        0
    DYN_WRM_RST_SPT_CFG:    0
    STA_POLICY_OP_IRQ_CFG:  0
    STA_POLICY_PWR_IRQ_CFG: 0
    LOCK_CFG:               0
    SW_DEV_DEL_CFG:         1
    PWR_MODE_ENTRY_DEL_CFG: 1
    DEF_OP_POLICY:          0b000
    NUM_OPMODE_CFG:         0
    DEF_OP_DYN_EN:          0
    OP_ACTIVE_CFG:          0
    DEV_SYNC_EN:            0
    DEV_ACTIVE_SYNC_EN:     0
    PCSM_SYNC_EN:           1
    QCLK_SYNC_EN:           1
    OFF_MEM_RET_TRANS_CFG:  0
    PCSM_OFF_INIT:          1
    OPMODE_PCSM_SPT_CFG:    0
    UARCH:                  1



