##------------------------------------------------------------------------------
## The confidential and proprietary information contained in this file may
## only be used by a person authorised under and to the extent permitted
## by a subsisting licensing agreement from Arm Limited or its affiliates.
##
##        (C) COPYRIGHT 2018-2021 Arm Limited or its affiliates.
##            ALL RIGHTS RESERVED
##
## This entire notice must be reproduced on all copies of this file
## and copies of this file may only be made by a person if such person is
## permitted to do so under the terms of a subsisting license agreement
## from Arm Limited or its affiliates.
##
##      Release Information : SSE710-r0p0-00rel0
##
##------------------------------------------------------------------------------
## Purpose : C test Makefile
##------------------------------------------------------------------------------
TESTCODES_BUILD_DIR = $(SOCLABS_MEGASOC_TECH_DIR)/software/build
BUILD_DIR        = $(TESTCODES_BUILD_DIR)/$(TEST_ID)
SCRIPTS_DIR      = $(SOCLABS_MEGASOC_TECH_DIR)/software/shared/tools/bin
MEM_IMG_PATH     = $(SCRIPTS_DIR)/memory_image_scripts

export BUILD_DIR
export MEM_IMG_PATH

# ------------------------------------------------------------------------------
# Default build target
# ------------------------------------------------------------------------------
.PHONY: all
all: print  get_host_image
	ln -sf $(SOCLABS_MEGASOC_TECH_DIR)/software/shared/bin/cxdt_empty.bin $(SOCLABS_MEGASOC_TECH_DIR)/software/shared/bin/cxdt.bin

boot_build: print get_boot_image
	ln -sf $(SOCLABS_MEGASOC_TECH_DIR)/software/shared/bin/cxdt_empty.bin $(SOCLABS_MEGASOC_TECH_DIR)/software/shared/bin/cxdt.bin

.PHONY: get_host_image
get_host_image:
	@echo -e "\n------------------- Executing make target $@ -------------------"
	make all -f $(SOCLABS_MEGASOC_TECH_DIR)/software/lib/common/Makefile.c_host
	@rm -rf $(BUILD_DIR)/host0; mkdir -p $(BUILD_DIR)/host0; mv $(BUILD_DIR)/*.v8-a.* $(BUILD_DIR)/obj $(BUILD_DIR)/host0

.PHONY: get_boot_image
get_boot_image:
	@echo -e "\n------------------- Executing make target $@ -------------------"
	make all_bootloader -f $(SOCLABS_MEGASOC_TECH_DIR)/software/lib/common/Makefile.c_host
	@rm -rf $(BUILD_DIR)/host0; mkdir -p $(BUILD_DIR)/host0; mv $(BUILD_DIR)/*.v8-a.* $(BUILD_DIR)/obj $(BUILD_DIR)/host0

.PHONY: print
print:
	@echo -e "\n------------------- Executing make target $@ -------------------"
	@echo "CURDIR    = $(CURDIR)"
	@echo "TEST_PATH = $(TEST_PATH)"
	@echo "TEST_ID   = $(TEST_ID)"

.PHONY: clean
clean:
	@echo -e "\n------------------- Executing make target $@ -------------------"
	@echo "Cleaning all build files"
	rm -rf $(BUILD_DIR)
